// <auto-generated />
using System;
using ConectaFranquias.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConectaFranquias.Api.Migrations
{
    [DbContext(typeof(ContextoFranquias))]
    partial class ContextoFranquiasModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriaId");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_Categorias_Nome_Unico");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.ChamadoSuporte", b =>
                {
                    b.Property<int>("ChamadoSuporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SolucaoAplicada")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioAberturaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChamadoSuporteId");

                    b.HasIndex("Protocolo")
                        .IsUnique()
                        .HasDatabaseName("IX_Chamados_Protocolo_Unico");

                    b.HasIndex("UnidadeId");

                    b.HasIndex("UsuarioAberturaId");

                    b.HasIndex("Situacao", "Prioridade");

                    b.ToTable("Chamados", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Estoque", b =>
                {
                    b.Property<int>("EstoqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdutoServicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeMinima")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EstoqueId");

                    b.HasIndex("ProdutoServicoId");

                    b.HasIndex("UnidadeId", "ProdutoServicoId")
                        .IsUnique()
                        .HasDatabaseName("IX_Estoques_Unidade_Produto_Unico");

                    b.ToTable("Estoques", null, t =>
                        {
                            t.HasCheckConstraint("CK_Estoques_Quantidade_NaoNegativa", "Quantidade >= 0");
                        });
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Fornecedor", b =>
                {
                    b.Property<int>("FornecedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("FornecedorId");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("IX_Fornecedores_Cnpj_Unico");

                    b.HasIndex("NomeFantasia");

                    b.ToTable("Fornecedores", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.FornecedorProduto", b =>
                {
                    b.Property<int>("FornecedorProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoServicoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FornecedorProdutoId");

                    b.HasIndex("ProdutoServicoId");

                    b.HasIndex("FornecedorId", "ProdutoServicoId")
                        .IsUnique()
                        .HasDatabaseName("IX_FornecedoresProdutos_Vinculo_Unico");

                    b.ToTable("FornecedoresProdutos", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Franqueado", b =>
                {
                    b.Property<int>("FranqueadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("FranqueadoId");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Franqueados_Cpf_Unico");

                    b.ToTable("Franqueados", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Franqueadora", b =>
                {
                    b.Property<int>("FranqueadoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("FranqueadoraId");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("IX_Franqueadoras_Cnpj_Unico");

                    b.ToTable("Franqueadoras", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.InteracaoChamado", b =>
                {
                    b.Property<int>("InteracaoChamadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChamadoSuporteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SituacaoAnterior")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SituacaoAtual")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InteracaoChamadoId");

                    b.HasIndex("ChamadoSuporteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("InteracoesChamado", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.ItemVenda", b =>
                {
                    b.Property<int>("ItemVendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoServicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemVendaId");

                    b.HasIndex("ProdutoServicoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItensVenda", null, t =>
                        {
                            t.HasCheckConstraint("CK_ItensVenda_Quantidade_Positiva", "Quantidade > 0");
                        });
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("MovimentacaoEstoqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstoqueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeAnterior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeResultante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovimentacaoEstoqueId");

                    b.HasIndex("EstoqueId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VendaId");

                    b.ToTable("MovimentacoesEstoque", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Perfil", b =>
                {
                    b.Property<int>("PerfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("PerfilId");

                    b.HasIndex("Tipo")
                        .IsUnique();

                    b.ToTable("Perfis", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.ProdutoServico", b =>
                {
                    b.Property<int>("ProdutoServicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ProdutoServicoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_ProdutosServicos_Codigo_Unico");

                    b.HasIndex("Nome");

                    b.ToTable("ProdutosServicos", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Responsavel", b =>
                {
                    b.Property<int>("ResponsavelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResponsavelId");

                    b.HasIndex("UnidadeId", "Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Responsaveis_Unidade_Cpf_Unico");

                    b.ToTable("Responsaveis", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Royalty", b =>
                {
                    b.Property<int>("RoyaltyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetenciaAno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetenciaMes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataApuracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FaturamentoBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PercentualAplicado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxaFranquia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorRoyalty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RoyaltyId");

                    b.HasIndex("UnidadeId", "CompetenciaAno", "CompetenciaMes")
                        .IsUnique()
                        .HasDatabaseName("IX_Royalties_Unidade_Competencia_Unico");

                    b.ToTable("Royalties", null, t =>
                        {
                            t.HasCheckConstraint("CK_Royalties_Percentual_Valido", "PercentualAplicado >= 0 AND PercentualAplicado <= 100");
                        });
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.UnidadeFranqueada", b =>
                {
                    b.Property<int>("UnidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicioContrato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("FranqueadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FranqueadoraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentualRoyalty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxaFranquiaMensal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UnidadeId");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("IX_Unidades_Cnpj_Unico");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Unidades_Codigo_Unico");

                    b.HasIndex("FranqueadoId");

                    b.HasIndex("FranqueadoraId");

                    b.ToTable("Unidades", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PerfilId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Email_Unico");

                    b.HasIndex("PerfilId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Venda", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroVenda")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VendaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UnidadeId", "DataVenda");

                    b.HasIndex("UnidadeId", "NumeroVenda")
                        .IsUnique()
                        .HasDatabaseName("IX_Vendas_Unidade_Numero_Unico");

                    b.ToTable("Vendas", (string)null);
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.ChamadoSuporte", b =>
                {
                    b.HasOne("ConectaFranquias.Api.Entities.UnidadeFranqueada", "Unidade")
                        .WithMany("Chamados")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConectaFranquias.Api.Entities.Usuario", "UsuarioAbertura")
                        .WithMany()
                        .HasForeignKey("UsuarioAberturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidade");

                    b.Navigation("UsuarioAbertura");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Estoque", b =>
                {
                    b.HasOne("ConectaFranquias.Api.Entities.ProdutoServico", "ProdutoServico")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConectaFranquias.Api.Entities.UnidadeFranqueada", "Unidade")
                        .WithMany("Estoques")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProdutoServico");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.FornecedorProduto", b =>
                {
                    b.HasOne("ConectaFranquias.Api.Entities.Fornecedor", "Fornecedor")
                        .WithMany("Produtos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaFranquias.Api.Entities.ProdutoServico", "ProdutoServico")
                        .WithMany("Fornecedores")
                        .HasForeignKey("ProdutoServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("ProdutoServico");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.InteracaoChamado", b =>
                {
                    b.HasOne("ConectaFranquias.Api.Entities.ChamadoSuporte", "Chamado")
                        .WithMany("Interacoes")
                        .HasForeignKey("ChamadoSuporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaFranquias.Api.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.ItemVenda", b =>
                {
                    b.HasOne("ConectaFranquias.Api.Entities.ProdutoServico", "ProdutoServico")
                        .WithMany()
                        .HasForeignKey("ProdutoServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConectaFranquias.Api.Entities.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoServico");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.MovimentacaoEstoque", b =>
                {
                    b.HasOne("ConectaFranquias.Api.Entities.Estoque", "Estoque")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaFranquias.Api.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConectaFranquias.Api.Entities.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estoque");

                    b.Navigation("Usuario");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.ProdutoServico", b =>
                {
                    b.HasOne("ConectaFranquias.Api.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Responsavel", b =>
                {
                    b.HasOne("ConectaFranquias.Api.Entities.UnidadeFranqueada", "Unidade")
                        .WithMany("Responsaveis")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Royalty", b =>
                {
                    b.HasOne("ConectaFranquias.Api.Entities.UnidadeFranqueada", "Unidade")
                        .WithMany("Royalties")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.UnidadeFranqueada", b =>
                {
                    b.HasOne("ConectaFranquias.Api.Entities.Franqueado", "Franqueado")
                        .WithMany("Unidades")
                        .HasForeignKey("FranqueadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConectaFranquias.Api.Entities.Franqueadora", "Franqueadora")
                        .WithMany("Unidades")
                        .HasForeignKey("FranqueadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ConectaFranquias.Api.Entities.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("UnidadeFranqueadaUnidadeId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("TEXT")
                                .HasColumnName("Bairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("TEXT")
                                .HasColumnName("Cep");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("TEXT")
                                .HasColumnName("Cidade");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Estado");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("Logradouro");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("TEXT")
                                .HasColumnName("Numero");

                            b1.HasKey("UnidadeFranqueadaUnidadeId");

                            b1.HasIndex("Cidade");

                            b1.ToTable("Unidades");

                            b1.WithOwner()
                                .HasForeignKey("UnidadeFranqueadaUnidadeId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("Franqueado");

                    b.Navigation("Franqueadora");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Usuario", b =>
                {
                    b.HasOne("ConectaFranquias.Api.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConectaFranquias.Api.Entities.UnidadeFranqueada", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Perfil");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Venda", b =>
                {
                    b.HasOne("ConectaFranquias.Api.Entities.UnidadeFranqueada", "Unidade")
                        .WithMany("Vendas")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConectaFranquias.Api.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.ChamadoSuporte", b =>
                {
                    b.Navigation("Interacoes");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Estoque", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Fornecedor", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Franqueado", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Franqueadora", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.ProdutoServico", b =>
                {
                    b.Navigation("Estoques");

                    b.Navigation("Fornecedores");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.UnidadeFranqueada", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("Estoques");

                    b.Navigation("Responsaveis");

                    b.Navigation("Royalties");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("ConectaFranquias.Api.Entities.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
